name: "Publish use case template"

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: "Publish use case template"

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout" 
      uses: actions/checkout@v4

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: "Build UseCases project"
      run: dotnet build ./UseCases/Template.UseCases.csproj

    - name: "Pack Use Case Template"
      run: dotnet pack ./UseCases/CreateExample/UseCaseTemplate.csproj -o ./packages -p:PackageVersion=1.0.${{ github.run_number }}

    - name: "Authenticate to Package Registry"
      run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: "Publish Use Case Template"
      run: dotnet nuget push ./packages/*.nupkg -k ${{ secrets.NUGET_FEED_KEY }} -s "github"
