name: "Publish use case template"

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: "Publish use case template"

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout" 
      uses: actions/checkout@v4

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: "Build UseCases project"
      run: dotnet build ./UseCases/Template.UseCases.csproj

    - name: "Pack Use Case Template"
      run: dotnet pack ./UseCases/CreateExample/UseCaseTemplate.csproj -o ./packages -p:PackageVersion=1.0.${{ github.run_number }}

    - name: "Publish Use Case Template"
      run: dotnet nuget push ./packages/*.nupkg -k ${{ github.token }} -s "https://nuget.pkg.github.com/${{github.repository}}/index.json"
